---
title: "smammalDataAnalyses"
output: pdf_document
---

```{r load libraries}

options(stringsAsFactors=F, strip.white=T)

library(stringr)
library(tidyr)
library(httr)
library(jsonlite)
library(plyr)
library(dplyr)
library(ggplot2)

```

```{r set working directory}

if (file.exists('/Users/kthibault/')){
  mypathtoTWGrepo <- '/Users/kthibault/Documents/GitHub/neonMammalTWG'
  mypathtoIPTrepo <- '/Users/kthibault/Documents/GitHub/organismalIPT'
}

setwd(mypathtoTWGrepo)

```


```{r load functions}

#function to pull published L1 small mammal box trapping data using the NEON API - returns only the capture data
source(paste(mypathtoTWGrepo, '/functions/getL1data.R', sep = ''))

if (file.exists('/Users/kthibault/')){
  #function to pull not yet published data from the Fulcrum database - available only to NEON personnel
  source(paste(mypathtoIPTrepo, '/smammal/scienceCode/getFulcrumData.R', sep = ''))
}

#function to group trapping nights by bout - bout IDs reflect the date of the nearest new moon
source(paste(mypathtoTWGrepo, '/functions/assignBoutIDs.R', sep = ''))

#function to add a number of taxonomic data fields to the capture data from the NEON master mammal taxon list, including scientific name and taxon rank
source(paste(mypathtoTWGrepo, '/functions/get.taxNames.taxonID.R', sep = ''))

#function to count the number of new species added to the list observed per plot per bout on the second and third nights of trapping relative to the previous night
source(paste(mypathtoTWGrepo, '/functions/countNewSpByNight.R', sep = ''))

#function to subset the dataset to include only one night of trapping for each pathogen grid per bout and/or only two nights
source(paste(mypathtoTWGrepo, '/functions/subsetDataToFewerNights.R', sep = ''))

#function to create a mean species accumulation curve with increasing number of plots across years of sampling per site
source(paste(mypathtoTWGrepo, '/functions/calcMeanSpecAccum.R', sep = ''))

#function to identify diversity and pathogen grids based on avergae nights of trapping per bout
source(paste(mypathtoTWGrepo, '/functions/classifyPlots.R', sep = ''))

#function to calculate plot-level observed species richness and iChao1 estimate
source(paste(mypathtoTWGrepo, '/functions/calculatePlotSpRichness.R', sep = ''))

#function to calculate site-level observed species richness and iChao1 estimate
source(paste(mypathtoTWGrepo, '/functions/calculateSiteSpRichness.R', sep = ''))

```

```{r load datafiles}

#use NEON API to get list of site codes with data
req <- GET("http://data.neonscience.org/api/v0/products/DP1.10072.001")
req.text <- content(req, as="text")
avail <- fromJSON(req.text, simplifyDataFrame=T, flatten=T)

#use NEON API to get the Level 1 data for the small mammal box trapping data product
captureDataL1 <- getL1data("DP1.10072.001", avail$data$siteCodes$siteCode)
# fix error discovered while working on bout id assignment
captureDataL1$collectDate[captureDataL1$plotID == 'UNDE_027' & captureDataL1$collectDate == '2015-08-31'] <- '2016-08-31'

#get latest field data from Fulcrum - available only to NEON personnel
if (exists(mypathtoIPTrepo)){
  ing.path <- paste(mypathtoIPTrepo, "/smammal/defData/mam_dataingest_NEON.DOC.001406.txt", sep ="")
  fulcrumData <- getFulcrumData(ing.path)
}

```

```{r combine L1 and Fulcrum data - NEON personnel only}

#subset Fulcrum data to only the capture records
captureDataFulcrum <- fulcrumData %>% filter(trapStatus == 4 | trapStatus == 5) %>% mutate(collectDate = startDate)
captureDataFulcrum$bloodSampleID <- toupper(captureDataFulcrum$bloodSampleID)
captureDataFulcrum$fecalSampleID <- toupper(captureDataFulcrum$fecalSampleID)
captureDataFulcrum$earSampleID <- toupper(captureDataFulcrum$earSampleID)
captureDataFulcrum$hairSampleID <- toupper(captureDataFulcrum$hairSampleID)
captureDataFulcrum$voucherSampleID <- toupper(captureDataFulcrum$voucherSampleID)

#get fields to align between L1 and Fulcrum data
namesToDel <- names(captureDataFulcrum)[!names(captureDataFulcrum) %in% names(captureDataL1)]
captureDataFulcrum$plotID <- gsub(".mammalGrid.mam", '', captureDataFulcrum$plotID)
captureDataFulcrum <- captureDataFulcrum %>% select(-which(names(captureDataFulcrum) %in% namesToDel))
captureDataFulcrum$uid <- NA
colsToAdd <- names(captureDataL1)[!names(captureDataL1) %in% names(captureDataFulcrum)]
captureDataL1 <- captureDataL1 %>% select(-which(names(captureDataL1) %in% colsToAdd))

#remove Fulcrum data with nightuids that are present in the L1 data already
nightsToDel <- unique(captureDataFulcrum$nightuid[captureDataFulcrum$nightuid %in% captureDataL1$nightuid])
captureDataFnew <- captureDataFulcrum %>% filter(!nightuid %in% nightsToDel)

#combine the two data sources
captureData <- rbind(captureDataL1, captureDataFnew)

write.csv(captureData, '/Users/kthibault/Documents/mamData20180120.csv', row.names = F)

```

```{r species added by night}

if (!exists('captureData')){
  if (file.exists('/Users/kthibault/')){
    captureData <- read.csv('/Users/kthibault/Documents/mamData20180120.csv')
    captureData <- captureData %>% select(-mo, -date, -year)
  } else {
    captureData <- captureDataL1
  }
}

captureData <- assignBoutIDs(captureData)
captureData <- get.taxNames.taxonID(captureData, mypathtoTWGrepo)

spByPlot <- captureData %>% filter(taxonRank == 'species' & taxonProtocolCategory == 'target') %>% distinct(boutID, collectDate, plotID, taxonID)

newSpAddedByNight <- countNewSpByNight(spByPlot)

plot(newSpAddedByNight$night, newSpAddedByNight$newTaxa)

ggplot(newSpAddedByNight, aes(x = night, y = newTaxa)) + 
  geom_boxplot() +
  facet_wrap(~siteID)

ggsave('newSpAddedByNightBySite.png')

ggplot(newSpAddedByNight, aes(x = night, y = newTaxa)) + 
  geom_boxplot()

ggsave('newSpAddedByNightAllSites.png')

```

```{r create datasets with varying nights of trapping}

#specify whether you want to subset the data to only 1 and/or 2 nights of trapping
n <- c(1,2)
subsetCaptureData <- subsetDataToFewerNights(captureData, n)
captureData1night <- subsetCaptureData[[1]]
captureData2night <- subsetCaptureData[[2]]

```

```{r compare species accumulation curves across nights of trapping}

library(vegan)

spaMean <- NULL
for (i in unique(captureData$siteID)){
  spaMean <- rbind(spaMean, calcMeanSpecAccum(captureData1night, i, '1nt'))
  spaMean <- rbind(spaMean, calcMeanSpecAccum(captureData2night, i, '2nt'))
  spaMean <- rbind(spaMean, calcMeanSpecAccum(captureData, i, 'all'))
  print(i)
}

ggplot(data = spaMean, mapping = aes(x = plots, y = meanS, group = dataset, color = dataset)) + geom_line() + facet_wrap(~siteID, scale = 'free')

ggsave('spAccumBySiteByNights.png')
       
```

```{r compare species accumulation curves between pathogen and diversity grids}

library(vegan)

plotTypes <- classifyPlots(captureData)
divPlots <- plotTypes[[1]]
pathPlots <- plotTypes[[2]]

divData <- captureData %>% filter(plotID %in% divPlots)
pathData <- captureData %>% filter(plotID %in% pathPlots)

spaMean <- NULL
for (i in unique(captureData$siteID)){
  spaMean <- rbind(spaMean, calcMeanSpecAccum(divData, i, 'diversity'))
  spaMean <- rbind(spaMean, calcMeanSpecAccum(pathData, i, 'pathogen'))
}

ggplot(data = spaMean, mapping = aes(x = plots, y = meanS, group = dataset, color = dataset)) + geom_line() + facet_wrap(~siteID)

ggsave('spAccumBySiteByPlotType.png')
       
```
```{r compare diversity estimates across nights and plot types}

#1. compare mean S per plot - observed vs iChao1 estimate - for each of the 3 datasets by site
allDataEstimates <- calculatePlotSpRichness(captureData, yearOI = '2016')
allDataEstimates$dataset <- 'all'
nt1Estimates <- calculatePlotSpRichness(captureData1night, yearOI = '2016')
nt1Estimates$dataset <- '1nt'
nt2Estimates <- calculatePlotSpRichness(captureData, yearOI = '2016')
nt2Estimates$dataset <- '2nt'
divEstimates <- rbind(allDataEstimates, nt1Estimates, nt2Estimates)
divEstimatesSonly <- divEstimates %>% filter(key == 'observedS' | key == 'Estimate')
divEstimatesSonly$key <- gsub('Estimate', 'iChao1', divEstimatesSonly$key)
divEstimatesSonly$key <- gsub('observedS', 'obs', divEstimatesSonly$key)
divEstimatesSonly <- divEstimatesSonly %>% rename(estimator = key, speciesRichness = value)

ggplot(divEstimatesSonly, aes(x = estimator, y = speciesRichness)) + geom_boxplot(aes(fill=dataset)) + facet_wrap(~siteID, scales = 'free_y')

ggsave('sEstimatesAcrossNights.png')


#2. compare observed vs. iChao1 estimate - Observed for each site for each of the 3 datasets
allDataEstimates <- calculateSiteSpRichness(captureData, yearOI = '2016')
allDataEstimates$dataset <- 'all'
nt1Estimates <- calculateSiteSpRichness(captureData1night, yearOI = '2016')
nt1Estimates$dataset <- '1nt'
nt2Estimates <- calculateSiteSpRichness(captureData, yearOI = '2016')
nt2Estimates$dataset <- '2nt'
divEstimates <- rbind(allDataEstimates, nt1Estimates, nt2Estimates)
divEstimatesSonly <- divEstimates %>% filter(key == 'observedS' | key == 'Estimate')
divEstimatesSonly$key <- gsub('Estimate', 'iChao1', divEstimatesSonly$key)
divEstimatesSonly$key <- gsub('observedS', 'obs', divEstimatesSonly$key)
divEstimatesSonly <- divEstimatesSonly %>% rename(estimator = key, speciesRichness = value)
divEstimatesSonlyDiff <- divEstimatesSonly %>% spread(estimator, speciesRichness) %>% mutate(diff = iChao1 - obs)

ggplot(divEstimatesSonlyDiff, aes(x = obs, y = diff)) + geom_point() + geom_text(aes(label = siteID), check_overlap =  T, vjust = -1, size=3) + ylab('iChao1 - Observed') + xlab('Observed Species Richness') + facet_grid(dataset~.)

ggsave('sSiteEstimatesAcrossNights.png')

#3. compare observed vs. iChao1 estimate for each site for the pathogen and diversity grids
plotTypes <- classifyPlots(captureData)
divPlots <- plotTypes[[1]]
pathPlots <- plotTypes[[2]]

divData <- captureData %>% filter(plotID %in% divPlots)
pathData <- captureData %>% filter(plotID %in% pathPlots)

divDataEstimates <- calculateSiteSpRichness(divData, yearOI = '2016')
pathDataEstimates <- calculateSiteSpRichness(pathData, yearOI = '2016')

divDataSonly <- divDataEstimates %>% filter(key == 'observedS' | key == 'Estimate')
divDataSonly$key <- gsub('Estimate', 'iChao1', divDataSonly$key)
divDataSonly$key <- gsub('observedS', 'obs', divDataSonly$key)
divDataSonly <- divDataSonly %>% rename(estimator = key, speciesRichness = value)
divDataSonly$dataset <- 'div'
#divDataSonlyDiff <- divDataSonly %>% spread(estimator, speciesRichness) %>% mutate(diff = iChao1 - obs)
pathDataSonly <- pathDataEstimates %>% filter(key == 'observedS' | key == 'Estimate')
pathDataSonly$key <- gsub('Estimate', 'iChao1', pathDataSonly$key)
pathDataSonly$key <- gsub('observedS', 'obs', pathDataSonly$key)
pathDataSonly <- pathDataSonly %>% rename(estimator = key, speciesRichness = value)
pathDataSonly$dataset <- 'path'
plotTypeEstimates <- rbind(divDataSonly, pathDataSonly)

ggplot(plotTypeEstimates, aes(dataset, speciesRichness)) + geom_bar(aes(fill=estimator), position = "dodge", stat="identity") + facet_wrap(~siteID, scales = 'free_y')

ggsave('sEstimatesAcrossPlotTypes.png')

```
```{r calculate number of recaptures within bouts and across bouts}
#from http://www.phidot.org/forum/viewtopic.php?f=36&t=1429
#It is critical to get enough recaptures. To estimate density at all by SECR you will probably need at least 10 recaptures, and 20 is a safer minimum. Aim for many more than the minimum! Precision improves with more recaptures, initially rapidly and then more slowly over 50 or so recaptures (e.g. Efford, Dawson & Robbins 2004 Fig. 2). Some studies have many recaptures of few animals (<20 individuals); estimation is possible, but confidence intervals will be very wide because of inherent spatial uncertainty (see below). To fit complicated models with covariates, finite mixtures, trends etc. you will need more data. 



```

```{r compare density estimates across nights of trapping}


#function calcSECRdensEstimate in progress

```
